---
dist: trusty
language: node_js
node_js:
  - "8"

env:
  global:
    - CC_TEST_REPORTER_ID=74bd25476cc9429c05fb4abe0771081c964d03ea13d84d4c604bd392f3834409

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run unit
# e2e tests don't run on travis-ci
# need to set up sauce labs
  - npm run build
# test that we haven't forgotten to build to dist/
  - pwd
  - git status
  - git diff-index --quiet HEAD --


after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
